In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/consumer_complaints/Consumer_Complaints.csv


In [37]:
file_path = '/kaggle/input/consumer_complaints/Consumer_Complaints.csv'
data = pd.read_csv(file_path)
print(data.head())
data = data[data['Consumer Complaint'].notna()]

  Date received           Product     Sub-product  \
0    03-12-2014          Mortgage  Other mortgage   
1    10-01-2016  Credit reporting             NaN   
2    10/17/2016     Consumer Loan    Vehicle loan   
3    06-08-2014       Credit card             NaN   
4    09/13/2014   Debt collection     Credit card   

                                      Issue                   Sub-issue  \
0  Loan modification,collection,foreclosure                         NaN   
1    Incorrect information on credit report              Account status   
2                Managing the loan or lease                         NaN   
3                                Bankruptcy                         NaN   
4                     Communication tactics  Frequent or repeated calls   

                                  Consumer Complaint  \
0                                                NaN   
1  I have outdated information on my credit repor...   
2  I purchased a new car on XXXX XXXX. The car de...   
3     

In [38]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [39]:
X=data["Consumer Complaint"].dropna()
y=data['Issue']

In [40]:
np.unique(y)

array(['APR or interest rate', 'Account opening, closing, or management',
       'Account terms and changes', 'Adding money', 'Advertising',
       'Advertising and marketing',
       'Advertising and marketing, including promotional offers',
       'Advertising, marketing or disclosures',
       'Application processing delay',
       'Application, originator, mortgage broker',
       'Applied for loan/did not receive money',
       'Applying for a mortgage',
       'Applying for a mortgage or refinancing an existing mortgage',
       'Arbitration', 'Attempts to collect debt not owed',
       'Balance transfer', 'Balance transfer fee', 'Bankruptcy',
       'Billing disputes', 'Billing statement', "Can't contact lender",
       "Can't contact lender or servicer", "Can't repay my loan",
       "Can't stop charges to bank account",
       "Can't stop withdrawals from your bank account", 'Cash advance',
       'Cash advance fee', 'Charged bank acct wrong day or amt',
       "Charged fees o

In [41]:
data.shape

(277814, 19)

In [42]:
vectorizer=TfidfVectorizer(max_features=5000,stop_words="english")

In [43]:
# X=X.dropna()

In [44]:
X=vectorizer.fit_transform(X)

In [45]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [35]:
mnb=MultinomialNB()

In [46]:
mnb.fit(X_train,y_train)

MultinomialNB()

In [48]:
y_pred=mnb.predict(X_test)

In [49]:
print("acc =",accuracy_score(y_pred,y_test))
print('confusion\n',confusion_matrix(y_test,y_pred))
print("report\n",classification_report(y_pred,y_test))

acc = 0.37445782265176464
confusion
 [[  2  27   0 ...   0   0   0]
 [  0 858   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   1   0 ...   0   0   0]
 [  0   5   0 ...   0  26   0]
 [  0   3   0 ...   0   0   0]]


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


report
                                                                                   precision    recall  f1-score   support

                                                            APR or interest rate       0.01      0.14      0.02        14
                                         Account opening, closing, or management       0.68      0.27      0.38      3213
                                                       Account terms and changes       0.00      0.00      0.00         0
                                                                    Adding money       0.00      0.00      0.00         0
                                                                     Advertising       0.00      0.00      0.00         0
                                                       Advertising and marketing       0.07      0.54      0.13        24
                         Advertising and marketing, including promotional offers       0.05      0.44      0.09        18
               

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
